compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
machine_rank: 0                  # 0 on master node, 1 on the other node
main_process_ip: fs-mbz-gpu-534  # IP or hostname of the master node
main_process_port: 8000          # A free port on master node (same on all nodes)
num_machines: 2
num_processes: 16               # Total GPUs (2 nodes × 8 GPUs)
mixed_precision: fp16           # or bf16 or no (depending on your preference)
use_cpu: false
rdzv_backend: static

